/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 reap/scene.gltf --transform 
Files: reap/scene.gltf [160KB] > C:\Users\franc\Desktop\Works\ReactAppTest\reactapp2\scene-transformed.glb [7.18MB] (-4385%)
Author: TooManyDemons (https://sketchfab.com/toomanydemons)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/reap-the-whirlwind-297e1595d6cf4466bf5c7803db8c5bd8
Title: Reap the Whirlwind
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Reaper(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(`/reap-transformed.glb`);
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  }, []);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.008}
      rotation={[0, 0.8, 0]}
    >
      <group name='Sketchfab_Scene'>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name='Object_9'
          geometry={nodes.Object_9.geometry}
          material={materials.M_Robot_Tail}
          skeleton={nodes.Object_9.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name='Object_10'
          geometry={nodes.Object_10.geometry}
          material={materials.M_Robot_Head}
          skeleton={nodes.Object_10.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name='Object_11'
          geometry={nodes.Object_11.geometry}
          material={materials.M_Robot_Cage}
          skeleton={nodes.Object_11.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name='Object_12'
          geometry={nodes.Object_12.geometry}
          material={materials.M_Robot_Legs}
          skeleton={nodes.Object_12.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name='Object_13'
          geometry={nodes.Object_13.geometry}
          material={materials.M_Robot_Foot}
          skeleton={nodes.Object_13.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name='Object_14'
          geometry={nodes.Object_14.geometry}
          material={materials.M_Robot_Wings_1}
          skeleton={nodes.Object_14.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name='Object_15'
          geometry={nodes.Object_15.geometry}
          material={materials.M_Robot_Wings_2}
          skeleton={nodes.Object_15.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name='Object_16'
          geometry={nodes.Object_16.geometry}
          material={materials.M_Robot_Arms}
          skeleton={nodes.Object_16.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name='Object_17'
          geometry={nodes.Object_17.geometry}
          material={materials.M_Robot_Gloves}
          skeleton={nodes.Object_17.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <skinnedMesh
          name='Object_18'
          geometry={nodes.Object_18.geometry}
          material={materials.Hologram}
          skeleton={nodes.Object_18.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(`/reap-transformed.glb`);
