/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 porsche_gt3_rs/scene.gltf --transform 
Files: porsche_gt3_rs/scene.gltf [562.02KB] > C:\Users\franc\Desktop\Works\ReactAppTest\reactapp2\scene-transformed.glb [1.78MB] (-217%)
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porsche-gt3-rs-e738eae819c34d19a31dd066c45e0f3d
Title: Porsche GT3 RS
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function ModelCar(props) {
  const { nodes, materials } = useGLTF(`/scene-transformed.glb`);
  return (
    <group {...props} dispose={null} scale={1.4}>
      <mesh
        geometry={
          nodes
            .TwiXeR_992_gt3rs_carbon_Wing_TwiXeR_992_plastic_mgl_060606FF001_0
            .geometry
        }
        material={materials.PaletteMaterial001}
        position={[0, 1.233, -2.098]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_gt3rs_carbon_Wing_TwiXeR_992_carbon_roof001_0
            .geometry
        }
        material={materials['TwiXeR_992_carbon_roof.001']}
        position={[0, 1.233, -2.098]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_gt3rs_carbon_hood_TwiXeR_992_metal_radiator002_0
            .geometry
        }
        material={materials['TwiXeR_992_metal_radiator.002']}
        position={[0, 0.725, 1.58]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={
          nodes[
            'TwiXeR_992_gt3rs_carbon_hood_TwiXeR_992_carPaint_secondary|hoodbadge_a001_0'
          ].geometry
        }
        material={materials['TwiXeR_992_headlight_1.001_0']}
        position={[0, 0.725, 1.58]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_gt3rs_sideskirts_L_TwiXeR_992_glass002_0.geometry
        }
        material={materials.PaletteMaterial002}
        position={[0.887, 0.321, 0.47]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_gt3rs_sideskirts_L_TwiXeR_992_headlight001_0.geometry
        }
        material={materials['TwiXeR_992_symbols.004']}
        position={[0.887, 0.321, 0.47]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_gt3rs_door_L_TwiXeR_992_rubbertrim004_0.geometry
        }
        material={materials['TwiXeR_992_headlight_1.001_1']}
        position={[0.795, 0.545, -0.069]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.TwiXeR_992_body_gt3rs_TwiXeR_992_plastic002_0.geometry}
        material={materials['TwiXeR_992_symbols.004_0']}
        position={[0.013, 0.786, -0.396]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_body_gt3rs_TwiXeR_992_ID10_chrome001_0.geometry
        }
        material={materials['TwiXeR_992_symbols_1.003']}
        position={[0.013, 0.786, -0.396]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_body_gt3rs_TwiXeR_992_undercarriage001_0.geometry
        }
        material={materials['TwiXeR_992_symbols.004_1']}
        position={[0.013, 0.786, -0.396]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_body_gt3rs_TwiXeR_992_ID12_paint001_0.geometry
        }
        material={materials['TwiXeR_992_symbols.004_2']}
        position={[0.013, 0.786, -0.396]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.TwiXeR_992_body_gt3rs_TwiXeR_992_roof_alc001_0.geometry}
        material={materials['TwiXeR_992_headlight_1.001_2']}
        position={[0.013, 0.786, -0.396]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_steer_3_TwiXeR_992_ID06_stitch_001_0.geometry
        }
        material={materials.TwiXeR_992_ID06_stitch_001}
        position={[0.345, 0.751, 0.192]}
        rotation={[-2.793, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.TwiXeR_992_steer_3_TwiXeR_992_carpet002_0.geometry}
        material={materials['TwiXeR_992_carpet.002']}
        position={[0.345, 0.751, 0.192]}
        rotation={[-2.793, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.TwiXeR_992_steer_3_TwiXeR_992_symbols_6_0.geometry}
        material={materials.TwiXeR_992_symbols_6}
        position={[0.345, 0.751, 0.192]}
        rotation={[-2.793, 0, Math.PI]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_body_chrome_end_TwiXeR_992_chrome003_0.geometry
        }
        material={materials['TwiXeR_992_chrome.003']}
        position={[0, 1.052, -0.609]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_dash_9000_TwiXeR_992_ID03_stitch_001_111111FF006_0
            .geometry
        }
        material={materials['TwiXeR_992_ID03_stitch_001_111111FF.006']}
        position={[0.126, 0.691, 0.302]}
      />
      <mesh
        geometry={nodes.TwiXeR_992_dash_9000_TwiXeR_992_plastic004_0.geometry}
        material={materials['TwiXeR_992_plastic.004']}
        position={[0.126, 0.691, 0.302]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_dash_9000_TwiXeR_992_seat_leather004_0.geometry
        }
        material={materials['TwiXeR_992_seat_leather.004']}
        position={[0.126, 0.691, 0.302]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_dash_9000_TwiXeR_992_upper_leather004_0.geometry
        }
        material={materials['TwiXeR_992_upper_leather.004']}
        position={[0.126, 0.691, 0.302]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_dash_9000_TwiXeR_992_gauges_9000001_0.geometry
        }
        material={materials['TwiXeR_992_gauges_9000.001_0']}
        position={[0.126, 0.691, 0.302]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_gauges_screen_TwiXeR_992_gauges_screen001_0.geometry
        }
        material={materials['TwiXeR_992_gauges_screen.001']}
        position={[0.338, 0.797, 0.367]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_headlight_L_led_TwiXeR_992_headlight_high001_0
            .geometry
        }
        material={materials.PaletteMaterial003}
        position={[0.697, 0.684, 1.612]}
      />
      <mesh
        geometry={
          nodes.TwiXeR_992_seat_FL_TwiXeR_992_seat_leather_2001_0.geometry
        }
        material={materials['TwiXeR_992_seat_leather_2.001']}
        position={[0.382, 0.578, -0.299]}
      />
    </group>
  );
}

useGLTF.preload(`/scene-transformed.glb`);
